type=page
status=published
title=Creating Custom Constraints
next=bean-validation-advanced002.html
prev=bean-validation-advanced.html
~~~~~~
# Creating Custom Constraints


[[GKFGX]]

[[creating-custom-constraints]]
Creating Custom Constraints
---------------------------

Bean Validation defines annotations, interfaces, and classes to allow
developers to create custom constraints.

The following topics are addressed here:

* link:#GKAIA[Using the Built-In Constraints to Make a New Constraint]
* link:#CIHCICAI[Removing Ambiguity in Constraint Targets]

[[GKAIA]]

[[using-the-built-in-constraints-to-make-a-new-constraint]]
Using the Built-In Constraints to Make a New Constraint
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bean Validation includes several built-in constraints that can be
combined to create new, reusable constraints. This can simplify
constraint definition by allowing developers to define a custom
constraint made up of several built-in constraints that may then be
applied to component attributes with a single annotation.

[[GKAJU]]

[source,oac_no_warn]
----
@Pattern.List({
  /* A number of format “+1-NNN-NNN-NNNN” */

@Pattern(regexp = “\\+1-\\d{3}-\\d{3}-\\d{4})

@Constraint(validatedBy = {})
@Documented
@Target({ElementType.METHOD,
    ElementType.FIELD,
    ElementType.ANNOTATION_TYPE,
    ElementType.CONSTRUCTOR,
    ElementType.PARAMETER
    ElementType.Type_Use})
@Retention(RetentionPolicy.RUNTIME)
@Repeatable(List.class)
public @interface USPhoneNumber {

String message() default "Not a valid US Phone Number";

Class<?>[] groups() default {};

Class<? extends Payload>[] payload() default {};


  @Target({ElementType.METHOD,
     ElementType.FIELD,
     ElementType.ANNOTATION_TYPE,
     ElementType.CONSTRUCTOR,
     ElementType.PARAMETER
     ElementType.Type_Use })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@interface List {
USPhoneNumber[] value();

}

}
----

You can also implement a `Constraint Validator` to validate the constraint `@USPhoneNumber`. For more information about using `Constraint Validator`, see `javax.validation.ConstraintValidator`.

[source,oac_no_warn]
----
@USPhoneNumber
protected String phone;
----

[[CIHCICAI]]

[[removing-ambiguity-in-constraint-targets]]
Removing Ambiguity in Constraint Targets
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Custom constraints that can be applied to both return values and method
parameters require a `validationAppliesTo` element to identify the
target of the constraint.

[source,oac_no_warn]
----
@Constraint(validatedBy=MyConstraintValidator.class)
@Target({ METHOD, FIELD, TYPE, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER })
@Retention(RUNTIME)
public @interface MyConstraint {
  String message() default "{com.example.constraint.MyConstraint.message}";
  Class<?>[] groups() default {};
  ConstraintTarget validationAppliesTo() default ConstraintTarget.PARAMETERS;
...
}
----

This constraint sets the `validationAppliesTo` target by default to the
method parameters.

[source,oac_no_warn]
----
@MyConstraint(validationAppliesTo=ConstraintTarget.RETURN_TYPE)
public String doSomething(String param1, String param2) { ... }
----

In the preceding example, the target is set to the return value of the
method.
