type=page
status=published
title=Building and Running the CDI Advanced Examples
next=cdi-adv-examples002.html
prev=cdi-adv-examples.html
~~~~~~
= Building and Running the CDI Advanced Examples


[[A1251406]]

[[building-and-running-the-cdi-advanced-examples]]
Building and Running the CDI Advanced Examples
----------------------------------------------

The examples are in the `_tut-install_/examples/cdi/` directory. To build
and run the examples, you will do the following.

1.  Use NetBeans IDE or the Maven tool to compile, package, and deploy
the example.
2.  Run the example in a web browser.

See link:usingexamples.html#GFIUD[Chapter 2, "Using the Tutorial
Examples"], for basic information on installing, building, and running
the examples.

The following topics are addressed here:

* link:cdi-adv-examples002.html#GKHPU[The encoder Example: Using
Alternatives]
* link:cdi-adv-examples003.html#GKHPY[The producermethods Example: Using
a Producer Method to Choose a Bean Implementation]
* link:cdi-adv-examples004.html#GKHRG[The producerfields Example: Using
Producer Fields to Generate Resources]
* link:cdi-adv-examples005.html#GKHPA[The billpayment Example: Using
Events and Interceptors]
* link:cdi-adv-examples006.html#GKPAX[The decorators Example: Decorating
a Bean]
