type=page
status=published
title=Using the Configurators Interfaces
next=cdi-bootstrap-se8.html
prev=cdi-adv009.html
~~~~~~
= Using the Configurators Interfaces

[[using-the-configurators-interfaces]]
Using the Configurators Interfaces
----------------------------------

The CDI 2.0 specification defines the following Configurators interfaces, which are used for dynamically defining and modifying CDI objects:

[width="99%",cols="30%,70%"]
|=======================================================================
|*Interface* |*Description*
|

`AnnotatedTypeConfigurator` SPI

a|Helps create and configure the following type metadata:

`AnnotatedType`

`AnnotatedField`

`AnnotatedConstructor`

`AnnotatedMethod`

`AnnotatedParameter`

a|`InjectionPointConfigurator` interface a|Helps configure an existing `InjectionPoint` instance

a|`BeanAttributesConfigurator` interface a|Helps configure a new `BeanAttributes` instance

a|`BeanConfigurator` interface a|Helps configure a new `Bean` instance

a|`ObserverMethodConfigurator` interface a| Helps configure an `ObserverMethod` instance

a|`ProducerConfigurator` interface a|Helps configure a `Producer` instance
|=======================================================================
