type=page
status=published
title=Duke's Bookstore Case Study Example
next=dukes-bookstore001.html
prev=partcasestudies.html
~~~~~~
Duke's Bookstore Case Study Example
===================================

[[GLNVI]]

[[dukes-bookstore-case-study-example]]
60 Duke's Bookstore Case Study Example
--------------------------------------


The Duke's Bookstore example is a simple e-commerce application that
illustrates some of the more advanced features of JavaServer Faces
technology in combination with Contexts and Dependency Injection for
Java EE (CDI), enterprise beans, and the Java Persistence API. Users can
select books from an image map, view the bookstore catalog, and purchase
books. No security is used in this application.

The following topics are addressed here:

* link:dukes-bookstore001.html#GLOAW[Design and Architecture of Duke's
Bookstore]
* link:dukes-bookstore002.html#GLQFD[The Duke's Bookstore Interface]
* link:dukes-bookstore003.html#GLPPQ[Running the Duke's Bookstore Case
Study Application]
