type=page
status=published
title=Running the Enterprise Bean Examples
next=ejb-basicexamples001.html
prev=ejb-gettingstarted003.html
~~~~~~
Running the Enterprise Bean Examples
====================================

[[GIJRB]]

[[running-the-enterprise-bean-examples]]
37 Running the Enterprise Bean Examples
---------------------------------------


This chapter describes the EJB examples. Session beans provide a simple
but powerful way to encapsulate business logic within an application.
They can be accessed from remote Java clients, web service clients, and
components running in the same server.

The following topics are addressed here:

* link:ejb-basicexamples001.html#A1250776[Overview of the EJB Examples]
* link:ejb-basicexamples002.html#BNBOD[The cart Example]
* link:ejb-basicexamples003.html#GIPVI[A Singleton Session Bean Example:
counter]
* link:ejb-basicexamples004.html#BNBOR[A Web Service Example:
helloservice]
* link:ejb-basicexamples005.html#BNBOY[Using the Timer Service]
* link:ejb-basicexamples006.html#BNBPJ[Handling Exceptions]
