type=page
status=published
title=JAX-RS: Advanced Topics and an Example
next=jaxrs-advanced001.html
prev=jaxrs-client003.html
~~~~~~
JAX-RS: Advanced Topics and an Example
======================================

[[GJJXE]]

[[jax-rs-advanced-topics-and-an-example]]
34 JAX-RS: Advanced Topics and an Example
-----------------------------------------


The Java API for RESTful Web Services (JAX-RS, defined in JSR 370) is
designed to make it easy to develop applications that use the REST
architecture. This chapter describes advanced features of JAX-RS. If you
are new to JAX-RS, see link:jaxrs.html#GIEPU[Chapter 32, "Building
RESTful Web Services with JAX-RS"] before you proceed with this chapter.

JAX-RS is integrated with Contexts and Dependency Injection for Java EE
(CDI), Enterprise JavaBeans (EJB) technology, and Java Servlet
technology.

The following topics are addressed here:

* link:jaxrs-advanced001.html#GKKRB[Annotations for Field and Bean
Properties of Resource Classes]
* link:jaxrs-advanced002.html#BABCJEDF[Validating Resource Data with Bean
Validation]
* link:jaxrs-advanced003.html#GKNAV[Subresources and Runtime Resource
Resolution]
* link:jaxrs-advanced004.html#GKNCY[Integrating JAX-RS with EJB
Technology and CDI]
* link:jaxrs-advanced005.html#GKQDA[Conditional HTTP Requests]
* link:jaxrs-advanced006.html#GKQBQ[Runtime Content Negotiation]
* link:jaxrs-advanced007.html#GKKNJ[Using JAX-RS with JAXB]
* link:jaxrs-advanced008.html#GKOIB[The customer Example Application]
