type=page
status=published
title=Introduction to Facelets
next=jsf-facelets001.html
prev=jsf-intro009.html
~~~~~~
Introduction to Facelets
========================

[[GIEPX]]

[[introduction-to-facelets]]
8 Introduction to Facelets
--------------------------


The term Facelets refers to the view declaration language for JavaServer
Faces technology. Facelets is a part of the JavaServer Faces
specification and also the preferred presentation technology for
building JavaServer Faces technology–based applications. JavaServer
Pages (JSP) technology, previously used as the presentation technology
for JavaServer Faces, does not support all the new features available in
JavaServer Faces in the Java EE platform. JSP technology is considered
to be a deprecated presentation technology for JavaServer Faces.

The following topics are addressed here:

* link:jsf-facelets001.html#GIJTU[What Is Facelets?]
* link:jsf-facelets002.html#GIPRR[The Lifecycle of a Facelets
Application]
* link:jsf-facelets003.html#GIPOB[Developing a Simple Facelets
Application: The guessnumber-jsf Example Application]
* link:jsf-facelets004.html#GIQXP[Using Facelets Templates]
* link:jsf-facelets005.html#GIQZR[Composite Components]
* link:jsf-facelets006.html#GIRGM[Web Resources]
* link:jsf-facelets007.html#BABHGBJI[Relocatable Resources]
* link:jsf-facelets008.html#BABHAHDF[Resource Library Contracts]
* link:jsf-facelets009.html#BABGECCJ[HTML5-Friendly Markup]


