type=page
status=published
title=Using JavaServer Faces Technology in Web Pages
next=jsf-page001.html
prev=jsf-el008.html
~~~~~~
Using JavaServer Faces Technology in Web Pages
==============================================

[[BNAQZ]]

[[using-javaserver-faces-technology-in-web-pages]]
10 Using JavaServer Faces Technology in Web Pages
-------------------------------------------------


Web pages (Facelets pages, in most cases) represent the presentation
layer for web applications. The process of creating web pages for a
JavaServer Faces application includes using component tags to add
components to the page and wire them to backing beans, validators,
listeners, converters, and other server-side objects that are associated
with the page.

This chapter explains how to create web pages using various types of
component and core tags. In the next chapter, you will learn about
adding converters, validators, and listeners to component tags to
provide additional functionality to components.

Many of the examples in this chapter are taken from
link:dukes-bookstore.html#GLNVI[Chapter 60, "Duke's Bookstore Case Study
Example."]

The following topics are addressed here:

* link:jsf-page001.html#BNARB[Setting Up a Page]
* link:jsf-page002.html#BNARF[Adding Components to a Page Using HTML Tag
Library Tags]
* link:jsf-page003.html#BNARC[Using Core Tags]
