type=page
status=published
title=Contexts and Dependency Injection for Java EE
next=cdi-basic.html
prev=bean-validation-advanced004.html
~~~~~~
Contexts and Dependency Injection for Java EE
=============================================

[[GJBNR]][[JEETT00131]]

[[part-v]]
Part V +
--------

[[contexts-and-dependency-injection-for-java-ee]]
Contexts and Dependency Injection for Java EE
---------------------------------------------

Part V explores Contexts and Dependency Injection for Java EE (CDI).
This part contains the following chapters:

* link:cdi-basic.html#GIWHB[Chapter 25, "Introduction to Contexts and
Dependency Injection for Java EE"]
* link:cdi-basicexamples.html#GJBLS[Chapter 26, "Running the Basic
Contexts and Dependency Injection Examples"]
* link:cdi-adv.html#GJEHI[Chapter 27, "Contexts and Dependency Injection
for Java EE: Advanced Topics"]
* link:cdi-bootstrap-se8.html#bootstrapping-a-cdi-container-in-java-se[Chapter 28, "Bootstrapping a CDI Container in Java SE"]
* link:cdi-adv-examples.html#GKHRE[Chapter 29, "Running the Advanced
Contexts and Dependency Injection Examples"]
