type=page
status=published
title=Overview of the Java Persistence Query Language
next=persistence-querylanguage002.html
prev=persistence-querylanguage.html
~~~~~~
Overview of the Java Persistence Query Language
===============================================

[[A1073303]]

[[overview-of-the-java-persistence-query-language]]
Overview of the Java Persistence Query Language
-----------------------------------------------

The query language uses the abstract persistence schemas of entities,
including their relationships, for its data model and defines operators
and expressions based on this data model. The scope of a query spans the
abstract schemas of related entities that are packaged in the same
persistence unit. The query language uses an SQL-like syntax to select
objects or values based on entity abstract schema types and
relationships among them.

This chapter relies on the material presented in earlier chapters. For
conceptual information, see link:persistence-intro.html#BNBPZ[Chapter 40,
"Introduction to the Java Persistence API"]. For code examples, see
link:persistence-basicexamples.html#GIJST[Chapter 41, "Running the
Persistence Examples."]
