type=page
status=published
title=Preface
next=partintro.html
prev=title.html
~~~~~~
= Preface


[[GEXAF]]

[[preface]]
Preface
-------

This tutorial is a guide to developing enterprise applications for the
Java Platform, Enterprise Edition 8 (Java EE 8), using GlassFish Server
Open Source Edition.

GlassFish Server Open Source Edition is the leading open-source and
open-community platform for building and deploying next-generation
applications and services. GlassFish Server Open Source Edition,
developed by the GlassFish project open-source community at
`https://javaee.github.io/glassfish/`, is the first compatible implementation of
the Java EE 8 platform specification. This lightweight, flexible, and
open-source application server enables organizations not only to
leverage the new capabilities introduced within the Java EE 8
specification, but also to add to their existing capabilities through a
faster and more streamlined development and deployment cycle. GlassFish
Server Open Source Edition is hereafter referred to as GlassFish Server.

The following topics are addressed here:

* link:#audience[Audience]
* link:#documentation-accessibility[Documentation Accessibility]
* link:#before-you-read-this-book[Before You Read This Book]
* link:#related-documentation[Related Documentation]
* link:#conventions[Conventions]
* link:#default-paths-and-file-names[Default Paths and File Names]

[[CIACGIBD]]

[[audience]]
Audience
~~~~~~~~

This tutorial is intended for programmers interested in developing and
deploying Java EE 8 applications. It covers the technologies comprising
the Java EE platform and describes how to develop Java EE components and
deploy them on the Java EE Software Development Kit (SDK).

[[CIAHFICG]]

[[documentation-accessibility]]
Documentation Accessibility
~~~~~~~~~~~~~~~~~~~~~~~~~~~

For information about Oracle's commitment to accessibility, visit the
Oracle Accessibility Program website at
`http://www.oracle.com/pls/topic/lookup?ctx=acc&id=docacc`.

[[sthref2]]

Access to Oracle Support

Oracle customers that have purchased support have access to electronic
support through My Oracle Support. For information, visit
`http://www.oracle.com/pls/topic/lookup?ctx=acc&id=info` or visit
`http://www.oracle.com/pls/topic/lookup?ctx=acc&id=trs` if you are
hearing impaired.

[[BNAAC]]

[[before-you-read-this-book]]
Before You Read This Book
~~~~~~~~~~~~~~~~~~~~~~~~~

Before proceeding with this tutorial, you should have a good knowledge
of the Java programming language. A good way to get to that point is to
work through the Java Tutorials
(`http://docs.oracle.com/javase/tutorial/index.html`).

[[GIPRL]]

[[related-documentation]]
Related Documentation
~~~~~~~~~~~~~~~~~~~~~

The GlassFish Server documentation set describes deployment planning and
system installation. To obtain documentation for GlassFish Server Open
Source Edition, go to `https://javaee.github.io/glassfish/documentation`.

The Java EE 8 API specification can be viewed at
`https://javaee.github.io/glassfish/documentation` and is also provided in the Java
EE 8 SDK.

Additionally, the Java EE Specifications at
`https://javaee.github.io/javaee-spec/` might be
useful.

For information about creating enterprise applications in the NetBeans
Integrated Development Environment (IDE), see
`https://netbeans.org/kb/`.

For information about Apache Derby for use with GlassFish
Server, see
`http://db.apache.org/derby/docs/10.13/adminguide/`.

The GlassFish Samples project is a collection of sample applications
that demonstrate a broad range of Java EE technologies. The GlassFish
Samples are bundled with the Java EE Software Development Kit (SDK) and
are also available from the GlassFish Samples project page at
`https://javaee.github.io/glassfish-samples/`.

[[GKVTF]]

[[conventions]]
Conventions
~~~~~~~~~~~

The following table describes the typographic conventions that are used
in this book.

[width="99%",cols="20%,38%,37%"]
|=======================================================================
|*Convention* |*Meaning* |*Example*
|*Boldface* |Boldface type indicates graphical user interface elements
associated with an action or terms defined in text. a|
From the *File* menu, choose *Open Project*.

A *cache* is a copy that is stored locally.

|`Monospace` |Monospace type indicates the names of files and
directories, commands within a paragraph, URLs, code in examples, text
that appears on the screen, or text that you enter. a|
Edit your `.login` file.

Use `ls -a` to list all files.

`_machine_name_% you have mail.`

|_Italic_ |Italic type indicates book titles, emphasis, or placeholder
variables for which you supply particular values. a|
Read Chapter 6 in the _User's Guide_.

Do _not_ save the file.

The command to remove a file is `rm _filename_`.

|=======================================================================


[[GFIRK]]

[[default-paths-and-file-names]]
Default Paths and File Names
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following table describes the default paths and file names that are
used in this book.

[width="99%",cols="20%,38%,38%"]
|=======================================================================
|*Placeholder* |*Description* |*Default Value*
|`_as-install_` |Represents the base installation directory for GlassFish
Server or the SDK of which GlassFish Server is a part. a|
Installations on the Solaris operating system, Linux operating system,
and Mac operating system:

`_user's-home-directory_/glassfish5/glassfish`

Windows, all installations:

`_SystemDrive_:\glassfish5\glassfish`

|`_as-install-parent_` |Represents the parent of the base installation
directory for GlassFish Server. a|
Installations on the Solaris operating system, Linux operating system,
and Mac operating system:

`_user's-home-directory_/glassfish5`

Windows, all installations:

`_SystemDrive_:\glassfish5`

|`_tut-install_` |Represents the base installation directory for the Java EE
Tutorial after you install GlassFish Server or the SDK and run the
Update Tool. |`_as-install-parent_/docs/javaee-tutorial`

|`_domain-dir_` |Represents the directory in which a domain's configuration
is stored. |`_as-install_/domains/domain1`
|=======================================================================
