type=page
status=published
title=Java API for Security
next=security-advanced.html
prev=security-api004.html
~~~~~~
= Running the Custom Identity Store Example


[[running-the-custom-identity-store-example]]
Running the Custom Identity Store Example
-----------------------------------------
The example described in this section demonstrates how to bundle and use a custom
identity store in your application for credential validation.

Topics include:

* link:#overview-of-the-custom-identity-store-example[Overview of the Custom Identity Store Example]
* link:#to-run-the-custom-identity-store-example[To Run the Custom Identity Store Example]

[[overview-of-the-custom-identity-store-example]]
Overview of the Custom Identity Store Example
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
As an alternative to using a built-in identity store, an application can provide
its own IdentityStore. When bundled with the application,
this custom identity store can then be used for authentication and authorization.

This example demonstrates how to define a custom identity store `TestIdentityStore` and
provide it as part of the application being deployed.

The following user and group are defined in this example.


[width=99%,cols="30%,40%,30%"]
|=======================================================================
|*User* |*Password* |*Group*

|Joe | secret1 | foo, bar |
|=======================================================================

When a request is made to the application with certain credentials, the configured
authentication mechanism comes into effect and authentication is performed
against the TestIdentityStore as defined in the application.

Post authentication, the application also verifies the roles the caller is in and
sends the details as part of the response.

The following code shows how you define the credentials and the roles assigned to users.

[source,oac_no_warn]
----
if (usernamePasswordCredential.compareTo("Joe", "secret1")) {
    return new CredentialValidationResult("Joe", new HashSet<>(asList("foo", "bar")));
}
----

The authentication mechanism, which gets invoked when a request is made, is
defined in `ApplicationConfig` as shown below:

[source,oac_no_warn]
----

@BasicAuthenticationMechanismDefinition(
        realmName = "file"
)

@ApplicationScoped
@Named
public class ApplicationConfig {

}

----
This example uses `BasicAuthenticationMechanism` as the authentication mechanism.
Note that in GlassFish, when `BasicAuthenticationMechanism` is used as the
authentication mechanism and the user provides the wrong credentials, the `realmName`
is presented to user, as a hint.

[source,oac_no_warn]
----
curl -I -u Joe http://localhost:8080/custom-identity-store/servlet
Enter host password for user 'Joe':
HTTP/1.1 401 Unauthorized
Server: GlassFish Server Open Source Edition  5.0
X-Powered-By: Servlet/3.1 JSP/2.3 (GlassFish Server Open Source Edition  5.0  Java/Oracle Corporation/1.8)
WWW-Authenticate: Basic realm="file"
Content-Length: 1090
Content-Language:
Content-Type: text/html
----


When a request is made to the application, the roles the user is in are
returned as part of the response.

[source,oac_no_warn]
----
@DeclareRoles({ "foo", "bar", "kaz" })
@WebServlet("/servlet")
public class Servlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        String webName = null;
        if (request.getUserPrincipal() != null) {
            webName = request.getUserPrincipal().getName();
        }

        response.getWriter().write("web username: " + webName + "\n");

        response.getWriter().write("web user has role \"foo\": " + request.isUserInRole("foo") + "\n");
        response.getWriter().write("web user has role \"bar\": " + request.isUserInRole("bar") + "\n");
        response.getWriter().write("web user has role \"kaz\": " + request.isUserInRole("kaz") + "\n");
    }

}
----
Note that the container needs to be made aware of the supported roles, which is
achieved with the help of the `@Declareroles` annotation as shown above.

[source,oac_no_warn]
----
@DeclareRoles({ "foo", "bar", "kaz" })
----
In GlassFish 5.0, group to role mapping is enabled by default. Therefore, you do
not need to bundle web.xml with the application to provide mapping between roles
and groups.

[[to-run-the-custom-identity-store-example]]
To Run the Custom Identity Store Example
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In this example, we are using the credentials of user `Joe` to make a request and
to validate the response according to the credentials defined in `TestIdentityStore`.

Steps:

1. Start the domain.
+
[source,oac_no_warn]
----
asadmin start-domain
----

2. Deploy the application.
+
[source,oac_no_warn]
----
asadmin deploy <project>/target/custom-identity-store.war
----

After the application is deployed, make a request to the application using the URL
shown below:

Request URL:
[source,oac_no_warn]
----
http://localhost:8080/custom-identity-store/servlet?name=Joe&password=secret1
----

Response:
[source,oac_no_warn]
----
web username: Joe
web user has role "foo": true
web user has role "bar": true
web user has role "kaz": false
----
If invalid credentials are used:

Request URL:
[source,oac_no_warn]
----
http://localhost:8080/custom-identity-store/servlet?name=Joe&password=secret3
----

Response:
[source,oac_no_warn]
----
HTTP Status 401 - Unauthorized

type Status report

message Unauthorized

description This request requires HTTP authentication.

GlassFish Server Open Source Edition 5
----
