type=page
status=published
title=Internationalizing and Localizing Web Applications
next=webi18n001.html
prev=jsonb004.html
~~~~~~
= Internationalizing and Localizing Web Applications


[[BNAXU]]

[[internationalizing-and-localizing-web-applications]]
22 Internationalizing and Localizing Web Applications
-----------------------------------------------------


The process of preparing an application to support more than one
language and data format is called internationalization. Localization is
the process of adapting an internationalized application to support a
specific region or locale. Examples of locale-dependent information
include messages and user interface labels, character sets and encoding,
and date and currency formats. Although all client user interfaces
should be internationalized and localized, it is particularly important
for web applications because of the global nature of the web.

The following topics are addressed here:

* link:webi18n001.html#BNAXV[Java Platform Localization Classes]
* link:webi18n002.html#BNAXW[Providing Localized Messages and Labels]
* link:webi18n003.html#BNAYA[Date and Number Formatting]
* link:webi18n004.html#BNAYB[Character Sets and Encodings]
